# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import recipes.utils.general


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170331_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images/recipes/default.jpg', upload_to=recipes.utils.general.path_and_rename('images/recipes')),
        ),
    ]
